apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xe32jslxt-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a29306fc93.iu31.p3.openshiftapps.com/rhtap/rhtap-qe:91e510b1419ee4a20881dcdc8c14a05e60f53f77@sha256:a240a8d72e079d972a95f38269e210972c0e83d0517ce007c2fe66fd9a9a765e
          name: container-image
